### ISSUE TITLE
Invalid pointer in Spine of chunk 6

### ISSUE THREAD

**Issue by zmbq** [FrankensteinVariorum/fv-data#14]
The following pointer in Spine 6 is invalid:

`<ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C06.xml#,1,2)"/> `

I see there are also four similar pointers in Spine 7 and  ten in Spine 8

**Comment by ebeshero** [comment]
@zmbq I’m starting to work on these now—I think we can correct most of these pointer issues quickly, as at least a couple are familiar.

**Comment by ebeshero** [comment]
@zmbq Solved, and in the process I discovered more in C07 and C08--they were not where I expected, or I had forgotten these *also* apply to 1831 as well as the MS witnesses. You can quickly see all the repaired locations here: 
https://github.com/PghFrankenstein/fv-data/commit/614994c03535b08b7a2eb99e357d4aef0fc1d0ad
