### ISSUE TITLE
Making hypothesis annotations public

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-data#20]
Sketching out two paths towards doing this for my own notes:

1. (ideal) Modify the `read` permissions on existing annotation to `group:__world__` via the API interface. Unfortunately, a few attempts I made at doing this with `PATCH` requests didn't seem to work. [I've pinged their mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!topic/dev/sQ0HKKVeRi4) and will wait to see if there's a response. This would be ideal, because then we can maintain the same identifier for annotations, and just happen to make them publicly viewable. The `frankensteinvariorum` user would still retain exclusive edit/delete permissions.

2. If it isn't possible to do a granular permissions change, then I would "migrate" the annotations by making new copies of them, posted to the public channel, and then delete the "private" annotations once they have public representations. I would do this to make sure that the team only ever has one version of an annotation to track, and so that we don't need to orchestrate constantly copying updates from private to public annotations.

**Comment by mdlincoln** [comment]
I've not gotten any response yet from the hypothesis mailing list, so I'm going to prep a script to do option 2.

**Comment by ebeshero** [comment]
@mdlincoln Before you get too deep in the weeds with this, shall we try pinging @judell who has responded to us here before re https://github.com/FrankensteinVariorum/fv-collation/issues/47 ?

**Comment by judell** [comment]
Hi folks,

The API won't support option #1.

Will this help for #2? https://jonudell.info/h/CopyAnnotations/

**Comment by robertknight** [comment]
> Modify the read permissions on existing annotation to group:__world__ via the API interface. 

That won't work I'm afraid. In the Hypothesis backend, groups and permissions actually work like this:

- All annotations belong to one group. They cannot currently be moved to another group after creation.
- Annotations have a boolean flag indicating whether they are visible only to the creator or shared with other members of the group

The `permissions` structure in API responses exists only for backwards compatibility, but you can't actually make use of the full flexibility implied by it.

**Comment by mdlincoln** [comment]
That's a useful clarification @robertknight - hope that can go into the API docs!

I've finished migrating the annotations.

**Comment by mdlincoln** [comment]
If the annotations team continues work in the future, perhaps the best way forward is:

1. they continue using the shared `frankensteinvariorum` account.
2. They make annotations in the "public" group, but visible only to that account, so they are effectively private
3. When an annotation is finished, the annotations team can then switch it to public using the interface
