### ISSUE TITLE
Create new group user for Hypothes.is; transfer annotations to new document under this user

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-data#6]
so they can edit each other's annotations

@scottbot will reach out to Matt Lavin, the original creator of the group, to get those permissions added.

**Comment by ebeshero** [comment]
Updating this issue after 2019-04-12 meeting. We need a shared user for collaborative editing of hypothes.is annotations. @mdlincoln

**Comment by ebeshero** [comment]
Closing this, because it's identical to https://github.com/PghFrankenstein/fv-postCollation/issues/6 just opened after the 2019-04-12 meetings.
